pipeline:
#   restore-cache:
#     image: drillster/drone-volume-cache
#     restore: true
#     mount:
#       - ./.yarn-cache
#       - ./node_modules
#     volumes:
#       - /tmp/cache:/cache

  install:
    image: node:lts
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

  testing:
    image: node:lts
    group: testing
    commands:
      - yarn run test

  lint:
    image: node:lts
    group: testing
    commands:
      - yarn run lint
