kind: pipeline
type: docker
name: build

steps:

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: test
  image: node
  commands:
  - yarn
  - yarn eslint

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: docker
name: deploy

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: test
  image: node
  commands:
  - yarn
  - yarn eslint

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  event:
  - promote
  target:
  - patch


---
kind: pipeline
type: docker
name: publish minor

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: publish minor
  image: node
  commands:
  - git config --global user.email "drone@toxblh.com"
  - git config --global user.name "Drone CI"
  - yarn
  - yarn minor

- name: npm
  image: plugins/npm
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email

- name: push commit
  image: appleboy/drone-git-push
  settings:
    ssh_key:
      from_secret: git_ssh
    branch: master
    remote: git@github.com:Toxblh/ClearScore.git
    commit: true
    followtags: true

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  event:
  - promote
  target:
  - minor

---
kind: pipeline
type: docker
name: publish patch

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: test
  image: node
  commands:
  - yarn
  - yarn patch

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  event:
  - promote
  target:
  - patch

---
kind: pipeline
type: docker
name: Publish major

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: test
  image: node
  commands:
  - yarn
  - yarn major

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  event:
  - promote
  target:
  - major
