kind: pipeline
type: docker
name: build

steps:

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: test
  image: node
  commands:
  - yarn
  - yarn eslint

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: docker
name: deploy

steps:
- name: test
  image: node
  commands:
  - yarn
  - yarn eslint
  - echo "Prod"

trigger:
  event:
  - promote
  target:
  - production
