kind: pipeline
type: docker
name: build

steps:
- name: test
  image: node
  commands:
  - yarn
  - yarn eslint

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: docker
name: deploy

steps:
- name: test
  image: node
  commands:
  - yarn
  - yarn eslint

trigger:
  event:
  - promote
  target:
  - production
